services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbhbm
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:rootpassword@mysql/dbhbm"
    ports:
      - "8000:8000"
    entrypoint: sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data: